CREATE TABLE MEMBER(
	NAME VARCHAR2(10),
	USERID VARCHAR2(10),
	PWD VARCHAR2(10),
	EMAIL VARCHAR2(20),
	PHONE CHAR(13),
	ADMIN NUMBER(1) DEFAULT 0, -- 0:사용자, 1:관리자
	JOINDATE DATE DEFAULT SYSDATE,
	PRIMARY KEY (USERID)
);

-- NAME 저장공간 20으로 변경
ALTER TABLE MEMBER MODIFY NAME VARCHAR2(20);

SELECT *
  FROM USER_TABLES;

 -- 접속한 계정의 테이블별 제약조건 검색
SELECT *
  FROM USER_CONSTRAINTS
 WHERE TABLE_NAME = 'MEMBER';

-- 접속한 계정의 테이블별 컬럼 조회
SELECT *
  FROM USER_TAB_COLUMNS
 WHERE TABLE_NAME = 'MEMBER';
 
-- TITLE TABLE 생성
CREATE TABLE TITLE(
	TITLE_NO NUMBER PRIMARY KEY,
	TITLE_NAME VARCHAR2(40)
);


-- DEPARTMENT TABLE 생성
CREATE TABLE DEPARTMENT(
	DEPT_NO NUMBER PRIMARY KEY,
	DEPT_NAME VARCHAR2(40),
	DEPT_FLOOR NUMBER
);


-- EMPLOYEE 테이블 생성
CREATE TABLE EMPLOYEE (
    EMP_NO   NUMBER,
    EMP_NAME VARCHAR2(20) NOT NULL,
    TNO      NUMBER,
    MANAGER  NUMBER,
    SALARY   NUMBER,
    DNO      NUMBER,
    EMAIL    VARCHAR2(60) NOT NULL,
    PASSWD   VARCHAR2(60) NOT NULL,
    REGDATE  DATE DEFAULT SYSDATE,
    TEL      CHAR(13),
    PIC_URL  VARCHAR2(100),
    CONSTRAINT EMPLOYEE_EMPNO_PK   PRIMARY KEY (EMP_NO),
    CONSTRAINT EMPLOYEE_TNO_FK     FOREIGN KEY (TNO)     REFERENCES TITLE(TITLE_NO) ON DELETE SET NULL, 
    CONSTRAINT EMPLOYEE_MANAGER_FK FOREIGN KEY (MANAGER) REFERENCES EMPLOYEE(EMP_NO),
    CONSTRAINT EMPLOYEE_SALARY_CK  CHECK (SALARY < 6000000),
    CONSTRAINT EMPLOYEE_DNO_FK     FOREIGN KEY (DNO) REFERENCES DEPARTMENT(DEPT_NO) ON DELETE CASCADE
);

SELECT * FROM EMPLOYEE;










